### ISSUE TITLE
Is there a call?

### ISSUE THREAD

**Issue by tuicemen** [bwssytems/ha-bridge#426]
I probably have missed this I'm sure it is in the code somewhere.
Is there http call we could make to the bridge to turn on/off/dim a device?
And if so what response should be expected back if any?

**Comment by bwssytems** [comment]
Yes there is. Since the bridge emulates a Hue Hub, it is http calls that control it. It is documented in the README here https://github.com/bwssytems/ha-bridge#hue-rest-api-usage

**Comment by tuicemen** [comment]
I've read threw that and still lost.
what do I put for username?
Can I turn on/off exec device types too or just lights?

**Comment by bwssytems** [comment]
So, that API is the one that the Echo or Google Home calls. For the username, you can use anything as it is agnostic for the call unlike the hue hub where the link button needs to be pressed to register. A call to change the state of  a ha-bridge device is PUT http://1.1.1.1:80/api/myname/lights/1/state with a body of {"on":true} where 1 is the ha-bridge device number that you see on the configuration screen.

**Comment by bwssytems** [comment]
to dim a device, the body is this {"bri":200} where 200 is a value between 1 and 254 for the value.

**Comment by tuicemen** [comment]
So if the device is a exec I'd replace lights with exec or does that stays as lights?
I'm getting a not found error
using  http://bridgeip:80/api/myname/lights/1/state{'on":true}

**Comment by bwssytems** [comment]
the device types inside the bridge do not matter. Remember that the Hue API is fixed and it does not change based on the devices inside. Follow the example above.

**Comment by tuicemen** [comment]
I'm obiously doing something wrong
still getting a 404
device is #1 and is an exec but I'm using lights
http://localhost:80/api/myname/lights/1/state{"on":true} results in a 404
I can manually switch on/off in the bridge(localhost:80)

**Comment by bwssytems** [comment]
Ahhh, please go Google Rest Server use as you are not yet understanding how web api's are working

**Comment by tuicemen** [comment]
Ok I had thought I could just type in the put in a web browser like I can for a get.
I created a small test app in c# and get back a OK but the device still doesn't turn on
I guess I still need to do some reading.

**Comment by bwssytems** [comment]
Install Postman for your Chrome browser and test with that. Curl Can also be used if you have a linux machine handy. It is ussing the HTTP construct of PUT with the URI of http://localhost:80/api/myname/lights/1/state and then the HTTP Body payload of {"on":true} which is not part of the URI but is part of the request portion of the HTTP call.

**Comment by tuicemen** [comment]
ok in postman depending on the body option used I either get:
[{"success":{"username":"8acbdf82291a43d598b396288b85dd7e"}}] or 
[{"error":{"type":"2","address":"/","description":"Could not add user."}}]
but in both cases the light never turns on
I'll play some more

**Comment by bwssytems** [comment]
Run that call twice in a row or I guess you'll need to call the add user call after that

**Comment by tuicemen** [comment]
I get [{"success":{"username":"8acbdf82291a43d598b396288b85dd7e"}}] either way,  Theuser ID returned is always different # though, and device state still never changes
Created a Vb.net app and it does the same so although the device isn't turning on I'm getting close (I think)

**Comment by tuicemen** [comment]
Today I updated to version 4.1.1 hoping that maybe that may make a difference.
It did though not the way I expected.
I can use get and post successfully, however all puts return an error.
It is possible that yesterday I was using post and getting the  [{"success":{"username":"........
As thats what I get using it instead of a put today :(
Is anyone able to do a successful put?

**Comment by bwssytems** [comment]
So, your message is not correct yet, please post

**Comment by tuicemen** [comment]
I guess not
 if I use put http://localhost:80/api/myname/lights/1/state with {"on";true} in the body I get:
[{"error":{"type": 6, "address": "/lights/1","description": "Error on calling out to device", "parameter": "/lights/1state"}}]
However just tried this again if I put  http://localhost:80/api/myname/lights/1/bridgeupdatestate
with {"on";true} in the body I get: [{"success":{"/lights/1/state/on":true}}] but nothing happens with the light (I don't think it should with that command anyways).
Haven't tried the update device put yet

**Comment by bwssytems** [comment]
Have you tested this form the configuration panel for Device 1?

**Comment by bwssytems** [comment]
Please post your device configuration

**Comment by tuicemen** [comment]
Just went to try from the bridge device id 1 has changed.
I'll run some more tests using a different id

**Comment by bwssytems** [comment]
Yes, the ID needs to be on from the configuration page. I was using 1 as an example.

**Comment by tuicemen** [comment]
Ok Checked configuration of device 1 there was an error it that script.
I think I was looking at the row number and not the ID number
I tested with another ID as I can't see device 1 and the Put returns proper response and light turns on/off
Man I feel so dumb!
Thanks for sticking with me on this.

**Comment by shrimantpatel** [comment]
It seems like you cannot set the state(on) to false with any value being passed for brightness E.g.:
{"on": false,"bri": 0}   , so here even though the brightness is set to zero it would never set the on to false when the state of the device is queried ..the responses are as below the first one is for setting  and the 2nd one was for a status query:

1. [{"success":{"/lights/12/state/on":false}},{"success":{"/lights/12/state/bri":0}}]
2. {"state":{"on":true,"bri":0,"alert":"none","reachable":true},"type":"Dimmable light","name":"DOWN","modelid":"LWB007","manufacturername":"Philips","uniqueid":"00:17:88:5E:D3:0C-0C","swversion":"66012040"}
